# Generated by Django 3.2.7 on 2021-09-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_order_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.user'),
        ),
    ]
